#' @title Read a VEGAS gene list
#'
#' @description Reads a text file containing output generated by the VEGAS
#' software
#'
#' @param fn Name of the file tor read
#' @param path Path to file, defaults to \code{.}
#' @param adjPermP FLag indicating whether to adjust the permutation p-values
#'        reported by VEGAS, see below. Defaults to \code{TRUE}.
#'
#' @details VEGAS returns permutation p-values that are exactly zero, which is
#' of course impossible. The read-in function adjusts this by including the
#' observed test statistic in the null-count.
#'
#' @return A data frame containing the data with extra class attribute \code{VEGAS}
#' @export
readVEGAS = function(fn, path=".", adjPermP=TRUE)
{
	fn = file.path(path, fn)
	ret = read.table(fn, header=TRUE)
	if (adjPermP) {
		ret$Pvalue = adjustPermP(ret$Pvalue, ret$nSim)
	}		
	class(ret) = c("VEGAS", "data.frame")
	ret
}

adjustPermP = function(p, N)
{
	(p*N+1)/(N+1)
}

#' Summarize VEGAS data
#'
#' Display a short summary of a VEGAS dataset
#'
#' @param x A VEGAS object
#' @param ... Other arguments, currently ignored
#'
#' @return The same object, invisibly
#' @export
summary.VEGAS = function(x, ...)
{
	n = nrow(x)
	dup = length(which(duplicated(x$Gene)))
	p = summary(x$Pvalue)

	cat(n, " genes total (", dup, " duplicate IDs)\n\n", sep="")
	cat("Genewise p-values:\n")
	print(p)

	invisible(x)
}	
	
showDuplicates = function(x) x[x$Gene %in% x$Gene[duplicated(x$Gene)], ]
dropDuplicates = function(x) x[!duplicated(x$Gene), ]

    
